version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: nest_app
    restart: always
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
    depends_on:
      mysql:
        condition: service_healthy
    expose:
      - "3000"  # Porta interna apenas, sem mapeamento externo
    dns:
      - 8.8.8.8
      - 1.1.1.1

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "443:443"  # Porta HTTPS
      - "80:80"    # Opcional: para redirecionar HTTP para HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Arquivo de configuração
      - ./certs:/etc/nginx/certs            # Pasta com os certificados
    depends_on:
      - app
